rules:
  description-empty: # Description shouldn't be empty
    level: warning
  subject-empty: # Subject line should exist
    level: error
  type-empty: # Type must not be empty
    level: error
  description-max-length: # Description should be at most 72 characters
    level: error
    length: 72
  type: # Type must be one of the following
    level: error
    options:
      - build
      - chore
      - ci
      - docs
      - feat
      - fix
      - perf
      - refactor
      - revert
      - style
      - test
